name: Zizmor

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
    types:
      - checks_requested
  schedule:
    - cron: "43 5 * * 1"
  workflow_dispatch:

permissions: write-all

jobs:
  zizmor:
    name: Run zizmor
    permissions: write-all
    uses: LCV-Ideas-Software/.github/.github/workflows/zizmor.yml@67ecbebba92a6973f889114d4b0d64596519a94f # zizmor/v2.3.0
